import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { glob } from 'glob'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, '..')
const publicDir = path.resolve(rootDir, 'public')

console.log('==> Step 1: Compiling HTML with HAM...')
execSync('ham build', { cwd: rootDir, stdio: 'inherit' })

console.log('==> Step 2: Bundling TypeScript & Assets with Rollup...')
execSync('npx rollup -c', { cwd: rootDir, stdio: 'inherit' })

console.log('==> Step 3: Making asset URLs fully relative for static hosting...')
// Process root HTML files
const rootHtmlFiles = glob.sync('public/*.html', { cwd: rootDir })
for (const relPath of rootHtmlFiles) {
  const filePath = path.resolve(rootDir, relPath)
  let content = fs.readFileSync(filePath, 'utf-8')
  content = content.replace(/href=["']\/assets\//g, 'href="./assets/')
  content = content.replace(/src=["']\/assets\//g, 'src="./assets/')
  fs.writeFileSync(filePath, content, 'utf-8')
}

// Process play HTML files
const playHtmlFiles = glob.sync('public/play/**/*.html', { cwd: rootDir })
for (const relPath of playHtmlFiles) {
  const filePath = path.resolve(rootDir, relPath)
  let content = fs.readFileSync(filePath, 'utf-8')
  content = content.replace(/href=["']\/assets\//g, 'href="../assets/')
  content = content.replace(/src=["']\/assets\//g, 'src="../assets/')
  fs.writeFileSync(filePath, content, 'utf-8')
}

// Process fintech HTML files
const fintechHtmlFiles = glob.sync('public/fintech/**/*.html', { cwd: rootDir })
for (const relPath of fintechHtmlFiles) {
  const filePath = path.resolve(rootDir, relPath)
  let content = fs.readFileSync(filePath, 'utf-8')
  // Map fintech-specific asset tags generated by HAM to the fintech assets folder
  content = content.replace(/href=["']\/assets\/css\/fintech\//g, 'href="./assets/css/')
  content = content.replace(/src=["']\/assets\/js\/fintech\//g, 'src="./assets/js/')
  content = content.replace(/href=["']\/assets\//g, 'href="./assets/')
  content = content.replace(/src=["']\/assets\//g, 'src="./assets/')
  fs.writeFileSync(filePath, content, 'utf-8')
}

console.log('==> Step 4: Exporting static build directly to repository root...')
// 1. Copy root HTML files to repository root
for (const relPath of rootHtmlFiles) {
  const fileName = path.basename(relPath)
  fs.copyFileSync(path.resolve(rootDir, relPath), path.resolve(rootDir, fileName))
  console.log(`  Exported ./${fileName}`)
}

// 2. Copy play/
if (fs.existsSync(path.resolve(publicDir, 'play'))) {
  fs.cpSync(path.resolve(publicDir, 'play'), path.resolve(rootDir, 'play'), { recursive: true })
  console.log('  Exported ./play/')
}

// 3. Copy assets/
if (fs.existsSync(path.resolve(publicDir, 'assets'))) {
  fs.cpSync(path.resolve(publicDir, 'assets'), path.resolve(rootDir, 'assets'), { recursive: true })
  console.log('  Exported ./assets/')
}

// 4. Copy fintech/
if (fs.existsSync(path.resolve(publicDir, 'fintech'))) {
  fs.cpSync(path.resolve(publicDir, 'fintech'), path.resolve(rootDir, 'fintech'), { recursive: true })
  console.log('  Exported ./fintech/')
}

// 5. Create .nojekyll in root
fs.writeFileSync(path.resolve(rootDir, '.nojekyll'), '')
console.log('  Created ./.nojekyll')

// 6. Clean up temporary public directory
if (fs.existsSync(publicDir)) {
  fs.rmSync(publicDir, { recursive: true, force: true })
  console.log('  Cleaned up temporary public/ directory')
}

console.log('==> Build complete! All static files are in the repository root.')
